# Generated by Django 6.1.1 on 2026-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('user_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
